version: "2"
services:
  web:
    image: composer
    command: php artisan serve --host="0.0.0.0"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    links:
      - db
      - redis
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "app"
  redis:
    image: redis
